name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy --verbose

  build:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build for release
        run: cargo build --verbose --release --target-dir target
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: glitch-artifacts-${{ matrix.os }}
          path: |
            target/release/glitch${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')  && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest # Any OS is fine
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts (ubuntu)
        uses: actions/download-artifact@v3
        with:
          name: glitch-artifacts-ubuntu-latest
          path: target/ubuntu
      - name: Download build artifacts (macOS)
        uses: actions/download-artifact@v3
        with:
          name: glitch-artifacts-macos-latest
          path: target/macos
      - name: Download build artifacts (Windows)
        uses: actions/download-artifact@v3
        with:
          name: glitch-artifacts-windows-latest
          path: target/windows
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            target/ubuntu/glitch* 
            target/macos/glitch* 
            target/windows/glitch*

  prerelease:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }} && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts (ubuntu)
        uses: actions/download-artifact@v3
        with:
          name: glitch-artifacts-ubuntu-latest
          path: target/ubuntu
      - name: Download build artifacts (macOS)
        uses: actions/download-artifact@v3
        with:
          name: glitch-artifacts-macos-latest
          path: target/macos
      - name: Download build artifacts (Windows)
        uses: actions/download-artifact@v3
        with:
          name: glitch-artifacts-windows-latest
          path: target/windows
      - name: Create Pre-Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: prerelease
          name: Pre-Release
          prerelease: true
          files: |
            target/ubuntu/glitch* 
            target/macos/glitch* 
            target/windows/glitch*
